---
# tasks file for validation
#
- block:

    - name: Add info to OS_MIG_STATUS
      ansible.builtin.lineinfile: 
        path: "{{ OS_MIG_STATUS }}"
        line: "VALILDATION: Start"
        state: present
        create: true

    - name: Print message 
      ansible.builtin.debug:
        msg: "***  VALIDATION Stage of RHEL Inplace Upgarde - Started   ***"

    - name: Include task - compare_pre_post_mig_sys_info.yml to compare pre and post system info 
      ansible.builtin.include_tasks: compare_pre_post_mig_sys_info.yml


    - name: Add info to OS_MIG_STATUS
      ansible.builtin.lineinfile: 
        path: "{{ OS_MIG_STATUS }}"
        line: "VALILDATION: Complete"
        state: present
        create: true

    - name: Print message 
      ansible.builtin.debug:
        msg: "***  VALIDATION Stage of RHEL Inplace Upgarde - Completed   ***"

  rescue:
  
    - name: Add info to OS_MIG_STATUS
      ansible.builtin.lineinfile: 
        path: "{{ OS_MIG_STATUS }}"
        line: "VALILDATION: Fail"
        state: present
        create: true

    - name: Print message
      ansible.builtin.debug:
        msg: "An error occured while valaidation"


