---
- block:

    - name: Allow root login 
      ansible.builtin.lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "^#PermitRootLogin yes"
        line: "PermitRootLogin yes"
        state: present
