---
# tasks file for upgrade
- block:

    - name: Add info to OS_MIG_STATUS
      ansible.builtin.lineinfile: 
        path: "{{ OS_MIG_STATUS }}"
        line: "UPGRADE: Start"
        state: present
        create: true

    - name: Print message 
      ansible.builtin.debug:
        msg: "***  LEAPP_UPGRADE Stage of RHEL Inplace Upgarde - Started   ***"

    - name: Initialize lock, logging, and common vars
      ansible.builtin.import_role:
        name: common
      vars:
        job_name: RIPU in-place OS upgrade
    
    - name: Include tasks for leapp upgrade
      ansible.builtin.include_tasks: leapp_upgrade.yml
      when: ansible_distribution_major_version|int >= 7
    
    - name: Include post upgrade validation
      ansible.builtin.include_tasks: upgrade_validation.yml
    
    - name: Include tasks for leapp post upgrade
      ansible.builtin.include_tasks: leapp_post_upgrade.yml
      when: ansible_facts.ansible_local.pre_ripu.distribution_major_version|int >= 7
    
    - name: Notify RIPU in-place OS upgrade is done handler
      ansible.builtin.assert:
        that: true
        quiet: true
      changed_when: true
      notify: RIPU in-place OS upgrade is done

    - name: Add info to OS_MIG_STATUS
      ansible.builtin.lineinfile: 
        path: "{{ OS_MIG_STATUS }}"
        line: "UPGRADE: Complete"
        state: present
        create: true

    - name: Print message 
      ansible.builtin.debug:
        msg: "***  LEAPP_UPGRADE Stage of RHEL Inplace Upgarde - Completed   ***"

  rescue:

    - name: Add info to OS_MIG_STATUS
      ansible.builtin.lineinfile: 
        path: "{{ OS_MIG_STATUS }}"
        line: "UPGRADE: Fail"
        state: present
        create: true

    - name: Print message
      ansible.builtin.debug:
        msg: "An error occurred in leapp upgrade"
...
