---
- block:

    - name: Add info to OS_MIG_STATUS
      ansible.builtin.lineinfile: 
        path: "{{ OS_MIG_STATUS }}"
        line: "UPDATE_AND_REBOOT: Start"
        state: present
        create: true

    - name: update-and-reboot | Ensure all updates are applied
      ansible.builtin.package:
        name: "*"
        state: latest # noqa package-latest
      register: updates_available
      async: "{{ async_timeout_maximum | int }}"
      poll: "{{ async_poll_interval | int }}"
    
    - name: update-and-reboot | Reboot when updates applied
      ansible.builtin.reboot:
        reboot_timeout: 7200
        post_reboot_delay: "{{ post_reboot_delay }}"
      when: updates_available.changed # noqa: no-handler

    - name: Add info to OS_MIG_STATUS
      ansible.builtin.lineinfile: 
        path: "{{ OS_MIG_STATUS }}"
        line: "UPDATE_AND_REBOOT: Complete"
        state: present
        create: true

  rescue:


    - name: Add info to OS_MIG_STATUS
      ansible.builtin.lineinfile: 
        path: "{{ OS_MIG_STATUS }}"
        line: "UPDATE_AND_REBOOT: Fail"
        state: present
        create: true

    - name: Print message
      ansible.builtin.debug:
        msg: "An error occurred while update a system and rebooting it"

...
