---
# tasks file for post_upgrade
- block:

    - name: Add info to OS_MIG_STATUS
      ansible.builtin.lineinfile: 
        path: "{{ OS_MIG_STATUS }}"
        line: "POST_UPGRADE: Start"
        state: present
        create: true

    - name: Print message 
      ansible.builtin.debug:
        msg: "***  POST_UPGRADE Stage of RHEL Inplace Upgarde - Started   ***"

    - name: Include task file to harden cron permission
      ansible.builtin.include_tasks: cron_permissions_hardening.yml

    - name: Install packages 
      ansible.builtin.include_role:
        name: common
        tasks_from: manage_packages.yml
      vars:
        v_action: "install"
        v_list_of_packages: "{{ packages_to_install | list }}"
      when: 
        - packages_to_install is defined 
        - packages_to_install | length > 0 

    - name: Enable and start systemd services
      ansible.builtin.include_role:
        name: common
        tasks_from: systemd_services.yml
      vars:
        v_action: "start"
        v_list_of_services: "{{ systemd_services_to_start }}"
        v_enable: true
      when: 
        - systemd_services_to_start is defined 
        - systemd_services_to_start | length > 0
    
    - name: Gather system info 
      ansible.builtin.include_role:
        name: common
        tasks_from: log_info.yml
      vars:
        v_analysis: 'post'

    - name: Disable permit root login 
      ansible.builtin.lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "^PermitRootLogin yes"
        line: "#PermitRootLogin yes"
        state: present
      when: permit_root_login_change | bool == true
    
    - name: Add info to OS_MIG_STATUS
      ansible.builtin.lineinfile: 
        path: "{{ OS_MIG_STATUS }}"
        line: "POST_UPGRADE: Complete"
        state: present
        create: true

    - name: Print message 
      ansible.builtin.debug:
        msg: "***  POST_UPGRADE Stage of RHEL Inplace Upgarde - Completed  ***"

  rescue:

    - name: Add info to OS_MIG_STATUS
      ansible.builtin.lineinfile: 
        path: "{{ OS_MIG_STATUS }}"
        line: "POST_UPGRADE: FAIL"
        state: present
        create: true

    - name: Print message
      ansible.builtin.debug:
        msg: "An error occured while performing post upgrade tasks"


