---
# vars file for analysis
leapp_enable_repos_args: "{{ ('--enablerepo ' + leapp_repos_enabled | default([], true) | join(' --enablerepo ')) if leapp_repos_enabled | length > 0 else '' }}"

result_filename: "/var/log/leapp/leapp-report.txt"

...
