---
- block:

    - name: Add info to OS_MIG_STATUS
      ansible.builtin.lineinfile: 
        path: "{{ OS_MIG_STATUS }}"
        line: "LEAPP_UPGRADE_PRE_ANALYSIS: Start"
        state: present
        create: true

    - name: analysis-leapp | Register to leapp activation key
      community.general.redhat_subscription:
        state: present
        activationkey: "{{ satellite_activation_key_leapp }}"
        org_id: "{{ satellite_organization }}"
        force_register: true
      notify: Register to pre leapp activation key
      when:
        - leapp_upgrade_type == 'satellite'
        - satellite_organization is defined
        - satellite_activation_key_leapp is defined
    
    - name: analysis-leapp | Install packages for preupgrade analysis on RHEL 7
      ansible.builtin.package:
        name: "{{ analysis_packages_el7 }}"
        enablerepo: "{{ analysis_repos_el7 }}"
        state: latest # noqa package-latest
      when: ansible_distribution_major_version|int == 7
    
    - name: analysis-leapp | Ensure leapp log directory exists
      ansible.builtin.file:
        path: /var/log/leapp
        state: directory
        owner: root
        group: root
        mode: "0755"
    
    - name: analysis-leapp | Populate leapp_answers file
      ansible.builtin.copy:
        content: "{{ leapp_answerfile }}"
        dest: /var/log/leapp/answerfile
        owner: root
        group: root
        mode: "0644"
      when: leapp_answerfile is defined
    
    - name: analysis-leapp | Leapp preupgrade report
      ansible.builtin.shell: >
        set -o pipefail;
        export PATH={{ os_path }};
        leapp preupgrade
        {{ leapp_preupg_opts }}
        {{ leapp_enable_repos_args }}
        2>&1 | tee -a {{ log_file }}
      changed_when: true
      register: leapp
      args:
        executable: /bin/bash
      async: "{{ async_timeout_maximum | int }}"
      poll: "{{ async_poll_interval | int }}"
      failed_when: "'report has been generated' not in leapp.stdout"
    
    - name: analysis-leapp | Include check_results_file.yml
      ansible.builtin.include_tasks: check_results_file.yml
    
    - name: analysis-leapp | Include the parse_leapp_report role to check for inhibitors
      ansible.builtin.include_role:
        name: parse_leapp_report

    - name: Add info to OS_MIG_STATUS
      ansible.builtin.lineinfile: 
        path: "{{ OS_MIG_STATUS }}"
        line: "LEAPP_UPGRADE_PRE_ANALYSIS: Complete"
        state: present
        create: true

  rescue:

    - name: Add info to OS_MIG_STATUS
      ansible.builtin.lineinfile: 
        path: "{{ OS_MIG_STATUS }}"
        line: "LEAPP_UPGRADE_PRE_ANALYSIS: Fail"
        state: present
        create: true

    - name: Print message
      ansible.builtin.debug:
        msg: "An error occured with leapp pre upgrade analysis"
...
