---
# tasks file for analysis
- block:
    - name: Add info to OS_MIG_STATUS
      ansible.builtin.lineinfile: 
        path: "{{ OS_MIG_STATUS }}"
        line: "LEAPP_ANALYSIS: Start"
        state: present
        create: true

    - name: Print message 
      ansible.builtin.debug:
        msg: "***  LEAPP_ANALYSIS Stage of RHEL Inplace Upgarde - Started   ***"

    - name: Initialize lock, logging, and common vars
      ansible.builtin.import_role:
        name: common
      vars:
        job_name: RIPU preupgrade analysis
    
    - name: /etc/ansible/facts.d directory exists
      ansible.builtin.file:
        path: /etc/ansible/facts.d
        state: directory
        mode: "0755"
        owner: root
        group: root
    
    - name: Capture current ansible_facts for validation after upgrade
      ansible.builtin.copy:
        content: "{{ ansible_facts | ansible.builtin.combine({'ansible_local': {}}) }}"
        dest: /etc/ansible/facts.d/pre_ripu.fact
        mode: "0644"
        owner: root
        group: root
    
    - name: Capture a list of non-rhel versioned packages
      ansible.builtin.shell:
        cmd: >-
          set -o pipefail;
          export PATH={{ os_path }};
          rpm -qa | grep -ve '[\.|+]el{{ ansible_distribution_major_version }}' |
          grep -vE '^(gpg-pubkey|libmodulemd|katello-ca-consumer)' |
          sort
      register: unsigned_packages_pre
      changed_when: false
      failed_when:
        - unsigned_packages_pre.rc != 0
        - unsigned_packages_pre.stderr != ""
    
    - name: Create fact with the non-rhel versioned packages list
      ansible.builtin.set_fact:
        non_rhel_packages: "{{ unsigned_packages_pre.stdout_lines }}"
    
    - name: Capture the list of non-rhel versioned packages in a separate fact file
      ansible.builtin.copy:
        content: "{{ non_rhel_packages }}"
        dest: /etc/ansible/facts.d/non_rhel_packages.fact
        mode: "0644"
        owner: root
        group: root
    
    - name: Include tasks for leapp preupgrade analysis
      ansible.builtin.include_tasks: analysis_leapp.yml
      when: ansible_distribution_major_version|int >= 7
    
    - name: Notify analysis report is done handler
      ansible.builtin.assert:
        that: true
        quiet: true
      changed_when: true
      notify: Preupgrade analysis report is done

    - name: Add info to OS_MIG_STATUS
      ansible.builtin.lineinfile: 
        path: "{{ OS_MIG_STATUS }}"
        line: "LEAPP_ANALYSIS: Complete"
        state: present
        create: true

    - name: Print message 
      ansible.builtin.debug:
        msg: "***  LEAPP_ANALYSIS Stage of RHEL Inplace Upgarde - Completed   ***"

  rescue:

    - name: Add info to OS_MIG_STATUS
      ansible.builtin.lineinfile: 
        path: "{{ OS_MIG_STATUS }}"
        line: "LEAPP_ANALYSIS: Fail"
        state: present
        create: true

    - name: Print message
      ansible.builtin.debug:
        msg: "An error occured in Leapp analysis" 
...
